/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#ff8291',
        'on-error': '#ffffff',
        'surface-container-highest': '#f0dfda',
        'on-secondary-container': '#76192c',
        'surface-variant': '#f0dfda',
        'on-primary-fixed-variant': '#5d3f3c',
        'on-secondary-fixed': '#40000f',
        'tertiary-fixed-dim': '#95d5a7',
        'primary-fixed-dim': '#e7bdb8',
        'surface-bright': '#fff8f6',
        'on-primary-container': '#bc9590',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#fceae5',
        'on-tertiary-fixed-variant': '#10512f',
        'on-error-container': '#93000a',
        'tertiary-container': '#003e20',
        'inverse-on-surface': '#ffede8',
        'on-tertiary-container': '#6dab80',
        'on-secondary-fixed-variant': '#832234',
        'surface-container-high': '#f6e4df',
        'outline': '#827472',
        'on-surface-variant': '#504443',
        'on-surface': '#221a17',
        'error': '#ba1a1a',
        'outline-variant': '#d4c3c1',
        'inverse-surface': '#382e2b',
        'on-secondary': '#ffffff',
        'primary': '#321917',
        'error-container': '#ffdad6',
        'surface-tint': '#775652',
        'secondary': '#a23a4a',
        'surface': '#fff8f6',
        'surface-dim': '#e8d6d1',
        'on-background': '#221a17',
        'tertiary-fixed': '#b0f1c2',
        'on-tertiary-fixed': '#00210f',
        'inverse-primary': '#e7bdb8',
        'secondary-fixed': '#ffdadb',
        'tertiary': '#002611',
        'primary-container': '#4a2e2b',
        'primary-fixed': '#ffdad6',
        'on-tertiary': '#ffffff',
        'background': '#fff8f6',
        'on-primary-fixed': '#2d1513',
        'surface-container-low': '#fff1ec',
        'secondary-fixed-dim': '#ffb2b9',
        'on-primary': '#ffffff',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '1.25rem',
        'space-md': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'gutter-mobile': '1rem',
        'gutter': '1.5rem',
        'margin': '3rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        serif: ['Playfair Display', 'serif'],
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'title-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'display-md-mobile': ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'display-md': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-md-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '700' }],
        'display-md': ['44px', { lineHeight: '52px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
