const ACTION_TYPES = {
  CREATE: "CREATE_TODO",
  DELETE: "DELETE_TODO",
  TOGGLE: "TOGGLE_TODO",

  LOADING: "TODOS_LOADING",
  ERROR: "TODOS_ERROR",
  SUCCESS: "TODOS_SUCCESS",
};

export default ACTION_TYPES;
